### PR TITLE
Add a min max voltage to the battery display

### PR DESCRIPTION
**Pull request by tomperrine**
A simple change to keep the min and max voltage and display them on the battery screen.

### CODE REVIEW

**Comment by charles-haynes** [comment]
Is this so that you can get more resolution on the display? I chose 4.2v-3.2v because that's the normal operating range of the battery so you get a visual indication of how much battery you have left.

**Comment by tomperrine** [comment]
it was a first step in labeling the axes - this can probably be cancelled

**Comment by charles-haynes** [comment]
Labelling the axes is a good idea.

**Comment by charles-haynes** [comment]
Yeah I think I'm going to decline this one. Please feel free to submit another with labels for the axes if you like.

**Pull request closed without merging**
